#! /bin/sh

# Auto Port
export PINTOS_PORT=${PINTOS_PORT:-1234}

# Path to GDB macros file.  Customize for your site.
GDBMACROS=/home/vagrant/code/pintos-riscv/src/misc/gdb-macros

GDBUSED=riscv64-unknown-elf-gdb

# Choose correct GDB.
GDB="cgdb -d $GDBUSED"

# Run GDB.
if test -f "$GDBMACROS"; then
	exec $GDB -ex "target remote localhost:$PINTOS_PORT" -x "$GDBMACROS" "$@"
else
	echo "*** $GDBMACROS does not exist ***"
	echo "*** Pintos GDB macros will not be available ***"
	exec $GDB "$@"
fi
