#! /bin/sh

# Path to GDB macros file.  Customize for your site.
GDBMACROS=/home/vagrant/.bin/gdb-macros


GDBUSED=riscv32-unknown-linux-gnu-gdb

# Choose correct GDB.
GDB=cgdb -d $GDBUSED

# Run GDB.
if test -f "$GDBMACROS"; then
	exec $GDB -x "$GDBMACROS" "$@"
else
	echo "*** $GDBMACROS does not exist ***"
	echo "*** Pintos GDB macros will not be available ***"
	exec $GDB "$@"
fi
