name: do-nothing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-riscv64-unknown-elf
        sudo apt-get install -y fzf
        sudo apt-get install -y qemu-system-misc

    - name: Build userprog
      working-directory: ./src/userprog
      run: make

    - name: Run do-nothing test
      run: |
        cd src/utils
        export PATH=$PATH:$(pwd)
        cd ../userprog
        pintos-test do-nothing | grep -q 'pass'
